# docker compose file with followig services
# mysql database server (db) version 8+
# petclinic application (petclinic) with image name petclinic:1.0
# port 9966 should be mapped to 9966 on petclinic container
# port 3306 should be mapped to 3306 on db container
# add environment variable MYSQL_DATABASE=petclinic to petclinic service
# add environment variable MYSQL_USER=root to petclinic service
# add environment variable MYSQL_PASSWORD=pass@word1 to petclinic service
# put services in a custom network called petclinic-network
# use version 3.8 for docker compose file version
# petclicnic service depends on db service

version: '3.8'
networks:
  petclinic-network:
    driver: bridge
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: pass@word1
      MYSQL_USER: root
      MYSQL_DATABASE: petclinic
      MYSQL_PASSWORD: pass@word1
    networks:
      - petclinic-network
  petclinic:
    image: petclinic:1.0
    ports:
      - 9966:9966
    environment:
      MYSQL_DATABASE: petclinic
      MYSQL_USER: root
      MYSQL_PASSWORD: pass@word1
      MYSQL_HOST: db
    depends_on:
      - db
    networks:
      - petclinic-network
    restart: on-failure:5
